"""S5 placeholders: kb/mcp/skills/bots

Revision ID: dbc95bcd42c7
Revises: bc0285d8069b
Create Date: 2026-07-22 01:35:45.172236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc95bcd42c7'
down_revision = 'bc0285d8069b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_collections_owner_id'), ['owner_id'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('transport', sa.String(), nullable=True),
    sa.Column('credential_enc', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_user_id'), ['user_id'], unique=False)

    op.create_table('skills_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_config_user_id'), ['user_id'], unique=False)

    op.create_table('bots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('kb_collection_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('welcome', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_collection_id'], ['kb_collections.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_owner_id'), ['owner_id'], unique=False)

    op.create_table('kb_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['kb_collections.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_documents_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_kb_documents_collection_id'))

    op.drop_table('kb_documents')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_owner_id'))

    op.drop_table('bots')
    with op.batch_alter_table('skills_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_config_user_id'))

    op.drop_table('skills_config')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_user_id'))

    op.drop_table('mcp_servers')
    with op.batch_alter_table('kb_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_collections_owner_id'))

    op.drop_table('kb_collections')
    # ### end Alembic commands ###
