"""baseline: full schema incl jobs queue

Revision ID: bc9b7fec52ce
Revises: 
Create Date: 2026-07-21 23:59:42.236121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9b7fec52ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_logs_user_id'), ['user_id'], unique=False)

    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('llm_providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('first_fail_at', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quota_mb', sa.Integer(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('llm_provider_id', sa.String(), nullable=True),
    sa.Column('security_question', sa.Text(), nullable=True),
    sa.Column('security_answer', sa.Text(), nullable=True),
    sa.Column('password_version', sa.Integer(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('prefs', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('access_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('download_granted_until', sa.DateTime(), nullable=True),
    sa.Column('download_granted_at', sa.DateTime(), nullable=True),
    sa.Column('single_download_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_tokens_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('chat_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)

    op.create_table('file_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_groups_owner_id'), ['owner_id'], unique=False)

    op.create_table('mask_mappings',
    sa.Column('mask_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('real_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mask_id')
    )
    with op.batch_alter_table('mask_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mask_mappings_user_id'), ['user_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('guard_status', sa.String(), nullable=True),
    sa.Column('guard_reason', sa.Text(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('original_dir', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['file_groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_locked_at'), ['locked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_owner_id'), ['owner_id'], unique=False)

    op.create_table('sync_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_user_id'), ['user_id'], unique=False)

    op.create_table('transfer_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_messages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_messages_user_id'))

    op.drop_table('transfer_messages')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_user_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_files_locked_at'))
        batch_op.drop_index(batch_op.f('ix_files_group_id'))
        batch_op.drop_index(batch_op.f('ix_files_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_files_content_hash'))

    op.drop_table('files')
    with op.batch_alter_table('mask_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mask_mappings_user_id'))

    op.drop_table('mask_mappings')
    with op.batch_alter_table('file_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_groups_owner_id'))

    op.drop_table('file_groups')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))

    op.drop_table('chat_history')
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_device_fingerprint'))

    op.drop_table('access_tokens')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('login_attempts')
    op.drop_table('llm_providers')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    op.drop_table('admins')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_logs_user_id'))

    op.drop_table('access_logs')
    # ### end Alembic commands ###
