"""agent platform: chat memory + traces

Revision ID: bc0285d8069b
Revises: bc9b7fec52ce
Create Date: 2026-07-22 00:46:46.434779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0285d8069b'
down_revision = 'bc9b7fec52ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_results', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pending_state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('trace_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_history_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_trace_id'))
        batch_op.drop_column('trace_id')
        batch_op.drop_column('pending_state')
        batch_op.drop_column('tool_results')

    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_traces_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_created_at'))

    op.drop_table('agent_traces')
    # ### end Alembic commands ###
